title: CS227
description: Advanced Topics in Database
theme: just-the-docs

url: https://liu-zeming.github.io/cs227

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
